<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <UseMaui>true</UseMaui>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Maui" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Maui.Controls" />
    <PackageReference Include="Microsoft.Maui.Essentials" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Xaml.Behaviors.Interactions" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.Maui.Essentials">
      <HintPath>..\..\..\..\..\..\..\..\home\david\.nuget\packages\microsoft.maui.essentials\11.0.0-preview.1.26107.1\lib\netstandard2.1\Microsoft.Maui.Essentials.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
